[package]
authors = ["Kornel <kornel@geekhood.net>", "Lode Vandevenne <lvandeve@gmail.com>"]
categories = ["multimedia::encoding", "multimedia::images"]
description = "Reading and writing PNG files without system dependencies. Pure Rust port of LodePNG."
documentation = "https://docs.rs/lodepng"
homepage = "https://lib.rs/crates/lodepng"
include = ["src/**/*", "COPYRIGHT", "README.md", "Cargo.toml"]
keywords = ["PNG","lodepng","encoder","decoder"]
license = "Zlib"
name = "lodepng"
readme = "README.md"
repository = "https://github.com/kornelski/lodepng-rust.git"
version = "3.7.2"
edition = "2021"
rust-version = "1.57"

[badges]
travis-ci = { repository = "kornelski/lodepng-rust" }

[dependencies]
libc = "0.2.126"
rgb = { version = "0.8.34", features = ["as-bytes"] }
flate2 = { version = "1.0.24", default-features = false }
crc32fast = "1.3.2"
fallible_collections = { version = "0.4.5", features = ["rust_1_57"] }

[workspace]
members = ["lodepng_unittest"]

[profile.test]
opt-level = 2

[profile.dev]
opt-level = 2

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["rust_backend"]
cfzlib = ["flate2/cloudflare_zlib"]
rust_backend = ["flate2/rust_backend"]
